<div class="contenedorTablaClubes">
        <table class="table table-dark table-striped table-hover">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Edad</th>
                    <th>Posición</th>
                    <th>Cantidad de goles</th>
                    <th>Club</th>
                    <th>Botones Administrador</th>

                </tr>
            </thead>
            <tbody>
            <?php foreach($jugadores as $jugador): ?>
                <tr>
                    <td>
                        <a href="jugador/<?php echo $jugador->id ?>">
                        <?= $jugador->Nombre ?>
                        </a>
                    </td>
                    <td>
                        <?= $jugador->Edad ?>
                    </td>
                    <td>
                        <?= $jugador->Posicion ?>
                    </td>
                    <td>
                        <?= $jugador->Cantidad_de_goles ?>
                    </td>
                    <td>
                        <?= $jugador->Nombre_club ?>
                    </td>
                    <td>
                        <a href="editarJugador/<?php echo $jugador->id ?>" class="btn btn-info">Editar</a> 
                        <a href="eliminarJugador/<?php echo $jugador->id ?>" class="btn btn-info">Eliminar</a> 
                    </td>
                </tr>
            <?php endforeach ?>
            </tbody>
        </table>
    </div>

<?php  require_once 'templates/footer.phtml'; ?>