<?php require_once './templates/header.phtml'; ?>
<h1>Clubes</h1>
<p>En la siguiente tabla se pueden visualizar los Clubes a los cuales pertenecen los jugadores de la Selección Argentina, asi como también información acerca de los mismos.</p>
<p>Ingrese a los links para ver qué jugadores juegan actualmente en cada Club.</p>
<div class="contenedorTablaClubes">
    <table class="table table-dark table-striped table-hover">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Fundación</th>
                <th>Títulos Nacionales</th>
                <th>Títulos Internacionales</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($clubes as $club) : ?>
                <tr>
                    <td>
                        <a href="club/<?php echo $club->id_club ?>">
                        <?= $club->Nombre_club ?>
                    </td>
                    <td>
                        <?= $club->Fundacion ?>
                    </td>
                    <td>
                        <?= $club->Titulos_nacionales ?>
                    </td>
                    <td>
                        <?= $club->Titulos_internacionales ?>
                    </td>
                </tr>
            <?php endforeach ?>
        </tbody>
    </table>
</div>
