<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
    <title>Document</title>
</head>

<body>
    <div class="card text-center">
        <div class="card-header">
            Alentamos nuestra selección!
        </div>
        <div class="card-body">
            <h5 class="card-title"> <img src="images/copadelmundo.jpg" alt="Copa del mundo" width="2%">¡Enterate mas sobre la celeste y blanca!<img src="images/copadelmundo.jpg" alt="Copa del mundo" width="2%"></h5>
            <p class="card-text"><img src="images/argentina.jpg" alt="Bandera de argentina" width="2%"> ¡A la Scaloneta la seguimos donde y cuando sea! <img src="images/argentina.jpg" alt="Bandera de argentina" width="2%"></p>
            <img src="images/argentina.jpg" alt="Bandera de argentina" width="4%">
            <a href="https://www.instagram.com/afaseleccion/" class="btn btn-primary" width="5%"> <img class="redes" src="images/instagram.jpg" alt="Instagram" width="5%"></a>
            <a href="https://twitter.com/Argentina" class="btn btn-primary" width="5%"><img class="redes" src="images/twitter.jpg" alt="Twitter" width="5%"></a>
            <a href="https://www.facebook.com/AFASeleccionArgentina?locale=es_LA" class="btn btn-primary" width="5%"><img class="redes" src="images/facebook.jpg" alt="Facebook" width="5%"></a>
            <a href="https://www.adidas.com.ar/" class="btn btn-primary" width="10%"><img class="redes" src="images/adidas.jpg" alt="Sponsor Adidas" width="2%"></a>
            <img src="images/argentina.jpg" alt="Bandera de argentina" width="3%">
        </div>
    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>

</html>