<div class="card text-center">
    <div class="card-header">
        Alentamos nuestra selección!
    </div>
    <div class="card-body">
        <h5 class="card-title"> <img src="images/copadelmundo.jpg" alt="Copa del mundo" width="2%">¡Enterate mas sobre la celeste y blanca!<img src="images/copadelmundo.jpg" alt="Copa del mundo" width="2%"></h5>
        <p class="card-text"><img src="images/argentina.jpg" alt="Bandera de argentina" width="2%"> ¡A la Scaloneta la seguimos donde y cuando sea! <img src="images/argentina.jpg" alt="Bandera de argentina" width="2%"></p>
    </div>
    <div class="container">
        <div class="row d-flex align-items-center">
            <div>
                <img src="images/argentina.jpg" alt="Bandera de Argentina" width="40px">
                
                    <a href="https://www.instagram.com/afaseleccion/" class="btn btn-primary">
                        <img src="images/instagram.jpg" alt="Instagram" width="30px">
                    </a>
                    <a href="https://twitter.com/Argentina" class="btn btn-primary">
                        <img src="images/twitter.jpg" alt="Twitter" width="30px">
                    </a>
                    <a href="https://www.facebook.com/AFASeleccionArgentina?locale=es_LA" class="btn btn-primary">
                        <img src="images/facebook.jpg" alt="Facebook" width="30px">
                    </a>
                    <a href="https://www.adidas.com.ar/" class="btn btn-primary">
                        <img src="images/adidas.jpg" alt="Sponsor Adidas" width="30px">
                    </a>
                
                <img src="images/argentina.jpg" alt="Bandera de Argentina" width="40px">
            </div>
        </div>
    </div>
</div>