<?php 
    require_once 'templates/header.phtml';
?>
<h1 class="tituloForm">EDITAR TABLA DE JUGADORES</h1>
    <div class="contenedorTabla">
        <form action="agregarJugador" method="POST">
            <label>Nombre</label>
            <input type="text" name="nombre" placeholder="Ingrese nombre" required>
            <label>Edad</label>
            <input type="number" name="edad" placeholder="Ingrese edad" required>
            <label>Posición</label>
            <input type="text" name="posicion" placeholder="Ingrese posición" required>
            <label>Cantidad de goles</label>
            <input type="number" name="goles" placeholder="Ingrese cantidad de goles">

            <label>Club al que pertenece</label>
            <select name="id_club" required>
                <option selected disabled>Selecciona un Club</option>
                <?php 
                    foreach ($clubes as $club) { ?>
                        <option value="<?php echo $club->id_club?>"><?php echo $club->Nombre_club ?></option>
                <?php } ?>
            </select>-

            <button>AGREGAR</button>
        </form>
    </div>

