<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <base href="<?php echo BASE_URL ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
    <title>Selección Argentina</title>
</head>

<body>
<header>
    <img src="images/pelota2.jpg" alt="Pelota Argentina" width= 100% height= auto>
            <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #226dd6 ">
        <div class="container-fluid">
             <a class="navbar-brand" href="home">
                <img src="images/afa1.png" alt="Logo AFA" width="40" height="auto">
             </a>
                <a class="navbar-brand" href="home">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="clubes">Clubes</a>
                    </li>
            <?php if (!isset($_SESSION['USER_ID'])) : ?>        
                    <li class="nav-item">
                        <a class="nav-link" href="login">Login</a>
                    </li>
            <?php  else :?>
                    <li class="nav-item">
                    <a class="nav-link" href="formularioJugadores">Formulario Jugadores</a>
                    </li>
                    <li class="nav-item">
                    <a class="nav-link" href="formularioClubes">Formulario Clubes</a>
                    </li>
                    <li class="nav-item">
                    <a class="nav-link" href="logout"> Logout </a>
                    </li>
                </ul>
            </div>
        </div>
             </nav>
        <?php endif ?>  
    </header>    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>