<?php require_once './templates/header.phtml'; ?>
<h1>Seleccion Argentina</h1>
<p>Este sitio web muestra la vista detallada del equipo actual de la Selección Argentina. En la siguiente tabla, se puede visualizar toda la información personal de los jugadores: su edad, nacionalidad, posición en la que juegan, cantidad de goles convertidos en la selección y el Club al cual pertenecen.</p>
<div class= "jugadores">
    <div class="contenedorTabla">
        <table class="table table-dark table-striped table-hover">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Edad</th>
                    <th>Posición</th>
                    <th>Cantidad de goles</th>
                    <th>Club</th>
                </tr>
            </thead>
            <tbody>
            <?php foreach($jugadores as $jugador): ?>
                <tr>
                    <td>
                        <?= $jugador->Nombre ?>
                    </td>
                    <td>
                        <?= $jugador->Edad ?>
                    </td>
                    <td>
                        <?= $jugador->Posicion ?>
                    </td>
                    <td>
                        <?= $jugador->Cantidad_de_goles ?>
                    </td>
                    <td>
                        <?= $jugador->id_club ?>
                    </td>
                </tr>
            <?php endforeach ?>
            </tbody>
        </table>
    </div>
    <div class="contenedorImg">
        <img src="images/argentina.jpeg" alt="Seleccion Argentina" class="img_seleccion">
    </div>
    <div>
</div>


