<?php require_once './templates/header.phtml'; ?>

<table class="table table-dark table-striped">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Edad</th>
            <th>Posición</th>
            <th>Cantidad de goles</th>
            <th>Club</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach($jugadores as $jugador): ?>
        <tr>
            <td>
                <?= $jugador->Nombre ?>
            </td>
            <td>
                <?= $jugador->Edad ?>
            </td>
            <td>
                <?= $jugador->Posicion ?>
            </td>
            <td>
                <?= $jugador->Cantidad_de_goles ?>
            </td>
            <td>
                <?= $jugador->id_club ?>
            </td>
        </tr>
    <?php endforeach ?>
    </tbody>


