<?php require 'templates/header.phtml' ?>

<div>
    <form method="POST" action="Login">
        <div class="form-login">
            <label for="email">Email</label>
            <input type="email" required class="form-control" id="email" name="email">
        </div>
        <div class="form-login">
            <label for="password">Password</label>
            <input type="password" id="password" name="password">
        </div>
        <button type="submit" class="btn btn-primary mt-3">Entrar</button>
    </form>
</div>

<?php require 'templates/footer.phtml' ?>