<?php require 'templates/header.phtml' ?>

<?php $password = "admin";
    $passwordEncriptado = password_hash ($password, PASSWORD_DEFAULT);
?>

 
    <form class="formLogin" method="POST" action="auth">
        <div class="form-login">
            <label for="email">Email</label>
            <input type="email" id="email" name="email">
        </div>
        <div class="form-login">
            <label for="password">Password</label>
            <input type="password" id="password" name="password">
        </div>
        <button type="submit" class="btn btn-primary mt-3">Entrar</button>
        <?php if ($error) : ?>
                <div class='alert alert-danger' role='alert'>
                    <?= $error ?>
                </div>
        <?php endif ?>
    </form>

<?php require 'templates/footer.phtml' ?>